# The Microsoft Store screenshots, as recipes rather than as prose.
#
# `take-shots.ps1` beside this takes a set given the recipes for it, and
# `screenshot.ps1` under that is the driver and knows nothing about Segler.
# Both are generated by ship and the same in every repository with a window to
# photograph. This file is the part that is Segler's - which document, which
# shot, and what has to happen in the window before the shutter. It is the
# Windows spelling of `packaging/macos/shots.sh`, which is the same split.
#
# Everything a person would change to retake the set lives at the top, and
# running it by hand on the Windows machine is the same command CI runs:
#
#     powershell -ExecutionPolicy Bypass -File packaging\windows\shots.ps1
#
# WHAT THE SET HAS TO SHOW, AND WHY
#
# Apple rejected the Mac four under guideline 2.3.3 - *the Mac screenshots do
# not show the actual app in use in the majority of the screenshots* - and the
# rejection was right. Nothing was selected in any of them, so the element pane
# read *Select an element on the page or in the structure* in all four, and no
# edit was under way. A frame of an editor with nothing selected is a frame of
# a viewer. The Windows four are that same set in its Windows spelling and the
# same criticism is true of them, so: something is selected in every shot below,
# and an edit is under way or just done in more than one.
#
# The coordinates are measured from the frame's top-left corner at the size
# declared here. Change the size and they all move; that is why the size is a
# constant beside them rather than an argument with a default.
#
# WHAT THE ASSOCIATION MEANS FOR WHAT IS PHOTOGRAPHED
#
# The document is opened through the shell, so what appears is whatever is
# registered for `.dclx` on this machine. With the MSIX installed that is the
# packaged build, which is what a person gets. With `install.ps1` run against a
# release binary it is that binary, which is what CI has. Both are this commit's
# application; say which one in `packaging/store-listing.md`.
#
# Author: David M. Anderson
# Built with AI assistance (Claude, Anthropic)

[CmdletBinding()]
param(
    # One plain capture of the document at rest, and nothing else. This is how
    # the coordinates below get measured: take it, open it, read the pixel of
    # each control off it, and fill the constants in.
    [switch] $Reference,
    [string] $OutDir
)

$ErrorActionPreference = 'Stop'

. "$PSScriptRoot\take-shots.ps1"

$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path

# --- the configuration ------------------------------------------------------

# 1366x768 is the Microsoft Store's minimum for a desktop screenshot, and a
# window this size looks like a window rather than like an advertisement.
$WIDTH = 1366
$HEIGHT = 768

# The document the review notes point at, which rides every release.
$DOCUMENT = Join-Path $root 'packaging\review\sailing-directions.dclx'

# The process the window belongs to, which the driver stops first so the frame
# holds this run's window and not a previous one's.
$PROCESS = 'segler-desktop'

# Where the shots land. Not committed: dist is where every built artefact goes.
if (-not $OutDir) { $OutDir = Join-Path $root 'dist\screenshots' }

# The controls, by what they do rather than by where they are, so a recipe
# below reads as the thing it is doing. Each is "X,Y" in the frame.
#
# All of these were read off a frame of this document at this size. Retake one
# when the window changes, rather than adjusting a number until a shot looks
# right:
#
#     powershell -ExecutionPolicy Bypass -File packaging\windows\shots.ps1 -Reference
#
$PAGE_IMAGE_PANEL = '423,40'   # the toolbar toggle for the page images
$NEXT_PAGE = '353,40'          # the toolbar's forward arrow
$THE_PICTURE = '620,440'       # the picture on page two, on the page itself
$A_TABLE_CELL = '956,385'      # Newlyn's high water, in the HW column
$A_PARAGRAPH = '600,139'       # the opening line under the title
$A_HEADING = '350,494'         # *Hazards*, the second-level heading on page one

# What the cell is corrected to. One digit away from what is in the document,
# so the frame reads as a correction rather than as a different number, and
# short enough to be typed before the shutter.
$CORRECTION = '-0:38'

# --- the shots --------------------------------------------------------------

# One shot to a line: name, then the actions that put the window into the state
# being photographed, in the order they are given.
#
#   click X,Y     press a control
#   double X,Y    press it twice inside the double-click interval, which is
#                 how a block in the document pane opens for typing
#   type TEXT     type
#   key NAME      one key, optionally with modifiers: ctrl+a, return
function Get-Shots {
    # Correcting a table cell in place: the cell open with the new value being
    # typed, the table selected, and the pane showing row, column and kind.
    Shot '01-correcting-a-cell' @(
        "double $A_TABLE_CELL", 'key ctrl+a', "type $CORRECTION")

    # The page image beside the document, a paragraph selected, and its located
    # box drawn over the scan with the same coordinates in the pane. The page
    # image panel is in the set because it is the one thing in this application
    # no other DocLang tool has.
    #
    # The paragraph is selected before the panel opens, not after. Opening the
    # panel narrows the document pane, so every coordinate in it moves, and
    # `$A_PARAGRAPH` was read off a frame with the panel shut.
    Shot '02-the-page-beside-the-document' @(
        "click $A_PARAGRAPH", "click $PAGE_IMAGE_PANEL")

    # The correction committed: the title carries the modified mark, Save and
    # Undo have come on, the status line says which cell changed, and a heading
    # is selected with its level, layer and box in reach.
    Shot '03-the-correction-committed' @(
        "double $A_TABLE_CELL", 'key ctrl+a', "type $CORRECTION", "click $A_HEADING")

    # Page two: the picture selected, its class, its caption, its box on the
    # scan, and its markup.
    Shot '04-a-picture-on-page-two' @(
        "click $NEXT_PAGE", "click $THE_PICTURE")
}

Take-Shots -Launch @('shell', $DOCUMENT) -Process $PROCESS `
    -Width $WIDTH -Height $HEIGHT -OutDir $OutDir -Reference:$Reference
